// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCO600vx3MPpZrA7-dKPB6ObR-Yt_Op8xw',
    appId: '1:206764932704:web:ab85e19ebec4f638a34d05',
    messagingSenderId: '206764932704',
    projectId: 'counterfirebase-ba8e1',
    authDomain: 'counterfirebase-ba8e1.firebaseapp.com',
    storageBucket: 'counterfirebase-ba8e1.appspot.com',
    measurementId: 'G-B0NH8QKMT6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkhfqM3JVPGEsriSQNwNB1W6LwG-HMbsw',
    appId: '1:206764932704:android:bed57d011f25b6cba34d05',
    messagingSenderId: '206764932704',
    projectId: 'counterfirebase-ba8e1',
    storageBucket: 'counterfirebase-ba8e1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxXDRlvin8myaQ8cpoXHKXN9xhEXmx6eo',
    appId: '1:206764932704:ios:aebc28cadf2b8955a34d05',
    messagingSenderId: '206764932704',
    projectId: 'counterfirebase-ba8e1',
    storageBucket: 'counterfirebase-ba8e1.appspot.com',
    iosClientId: '206764932704-2ftv899q7lr69e6gb3ianf4ap87d7r1j.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxXDRlvin8myaQ8cpoXHKXN9xhEXmx6eo',
    appId: '1:206764932704:ios:aebc28cadf2b8955a34d05',
    messagingSenderId: '206764932704',
    projectId: 'counterfirebase-ba8e1',
    storageBucket: 'counterfirebase-ba8e1.appspot.com',
    iosClientId: '206764932704-2ftv899q7lr69e6gb3ianf4ap87d7r1j.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );
}
